/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#0061a5",
        "on-primary": "#ffffff",
        "primary-container": "#0099ff",
        "on-primary-container": "#002f54",
        secondary: "#cc4400",
        "on-secondary": "#ffffff",
        surface: "#faf8ff",
        "on-surface": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-surface-variant": "#3f4753",
        outline: "#707884",
        "outline-variant": "#bfc7d5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        tertiary: "#5c5f61",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "accent-green": "#4ade80",
        "accent-orange": "#cc4400",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "unit-1": "4px",
        "unit-2": "8px",
        "unit-4": "16px",
        "unit-6": "24px",
        "unit-8": "32px",
        "unit-12": "48px",
        "unit-16": "64px",
        "unit-20": "80px",
        "unit-24": "96px",
        "grid-gutter": "24px",
        "grid-margin": "32px",
        base: "4px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "metric-lg": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
        "headline-xl": ["Montserrat"],
        "label-mono": ["JetBrains Mono"],
        "headline-md": ["Montserrat"],
        "body-sm": ["Hanken Grotesk"],
        "headline-lg": ["Montserrat"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "metric-lg": ["20px", { lineHeight: "1.0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "800" }],
      },
      keyframes: {
        "status-glow": {
          "0%": { boxShadow: "0 0 0 0 rgba(0, 110, 47, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(0, 110, 47, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(0, 110, 47, 0)" },
        },
      },
      animation: {
        "status-pulse": "status-glow 2s infinite",
      },
    },
  },
  plugins: [],
}
