/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8fafc",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#e8edf2",
        "surface-container-high": "#e2e7ec",
        "surface-container-highest": "#dce1e6",
        "surface-variant": "#e2e6ea",
        background: "#f8fafc",
        "on-background": "#1c1b1b",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#64748b",
        primary: "#2a5b7d",
        "on-primary": "#ffffff",
        "primary-container": "#3a6b8d",
        "on-primary-container": "#ffffff",
        "primary-fixed": "#cbe6ff",
        "on-primary-fixed": "#001e30",
        "primary-fixed-dim": "#9dccf3",
        "on-primary-fixed-variant": "#154b6c",
        "inverse-primary": "#9dccf3",
        secondary: "#505f76",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-on-surface": "#f3f0ef",
        "inverse-surface": "#313030",
        outline: "#e2e8f0",
        "outline-variant": "#e2e8f0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        tertiary: "#5a3800",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#754f14",
        "on-tertiary-container": "#f8c37e",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#f2bd78",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#633f03",
        "surface-tint": "#336385",
        "accent-green": "#4ade80",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "unit-1": "4px",
        "unit-2": "8px",
        "unit-4": "16px",
        "unit-6": "24px",
        "unit-8": "32px",
        "unit-12": "48px",
        "unit-16": "64px",
        "unit-20": "80px",
        "unit-24": "96px",
        "grid-gutter": "24px",
        "grid-margin": "32px",
        base: "4px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "metric-lg": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "label-mono": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "metric-lg": ["20px", { lineHeight: "1.0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      keyframes: {},
      animation: {},
    },
  },
  plugins: [],
}
